language: python
cache: pip
python:
- '3.6'
notifications:
  email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - pip install pytest
  - wget -O watdiv.10M.hdt $WATDIV_LINK
  - wget -O watdiv.10M.hdt.index.v1-1 $WATDIV_INDEX_LINK
  - cp watdiv.10M.hdt tests/data/watdiv.10M.hdt
  - cp watdiv.10M.hdt.index.v1-1 tests/data/watdiv.10M.hdt.index.v1-1
install:
  - pip install pybind11
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest
before_deploy:
  - rm -rf build/
  - rm -rf tests/
deploy:
- provider: pypi
  skip_cleanup: true
  user: callidon
  password: $PYPI_PASSWD
  on:
    tags: true
