name: Python packaging 🐍
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish 📦 to PyPI
      uses: JRubics/poetry-publish@v1
      with:
        pypi_token: ${{ secrets.PYPI_API_TOKEN }}
