name: 🔍 Code quality and security
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} 🐍
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install flake8
      run: pip install flake8
    - name: (1/2) Lint with flake8
      run: flake8 sage/ --exclude protobuf --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: (2/2) Lint with flake8
      run: flake8 sage/ --exclude protobuf --count --max-complexity=10 --max-line-length=127 --statistics
